#! /bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &

if [[ $(xrandr -q | grep 'HDMI-0 connected') ]]; then 
	xrandr --output eDP-1-1 --primary --mode 1920x1080 --rotate normal --output HDMI-0 --mode 1920x1080 --rotate normal --right-of eDP-1-1
	# xrandr --output eDP-1-1 --mode 1920x1080 --rotate normal --output HDMI-0 --primary --mode 2580x1080 --rotate normal --above eDP-1-1
  bspc monitor eDP-1-1 -d 1 2 3 4 5
  # bspc monitor HDMI-0 -d 1 2 3 4 5
  bspc monitor HDMI-0 -d 6 7 8 9 0
  # bspc monitor eDP-1-1 -d 6 7 8 9 0
else
  bspc monitor eDP-1-1 -d 1 2 3 4 5 6 7 8 9 0
fi

bspc config border_width        2
bspc config window_gap          5
bspc config top_padding 	5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config click_to_focus          true
bspc config focus_follows_pointer   true
bspc config pointer_modifier mod1
bspc config pointer_action1 move

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
feh --bg-fill /home/elian/Documents/fondopantalla/linux-kernel.jpg
~/.config/polybar/./launch.sh
picom --experimental-backends &
bspc config border_width 0
